### ISSUE TITLE
[Question] Accepting PRs for injectors for other browser automation solutions?

### ISSUE THREAD

**Issue by michaeleveringham** [daijro/browserforge#9]
I was going to open a PR to add an injector for [mokr](https://github.com/michaeleveringham/mokr) (which I am the author of), but figured I'd check to see if you were open to additional injectors first.

**Comment by daijro** [comment]
Sure! I'd be happy for support to be added for mokr, it's a very neat package!

However, changes to the injector submodule might be moved to a separate repo soon (#7).
